builds:
  - skip: true
checksum:
  name_template: '{{ .ProjectName }}_sha256_checksums.txt'
  algorithm: sha256
  extra_files:
  - glob: ./release/linux-amd64/*.zip
  - glob: ./release/darwin-amd64/*.zip
  - glob: ./release/darwin-arm64/*.zip 
  - glob: ./release/windows-amd64/*.zip
release:
  # Same as for github
  # Note: it can only be one: either github, gitlab or gitea
  github:
    owner: hugokung
    name: micro_gateway

  draft: false

  # You can add extra pre-existing files to the release.
  # The filename on the release will be the last part of the path (base). If
  # another file with the same name exists, the latest one found will be used.
  # Defaults to empty.
  extra_files:
    - glob: ./release/linux-amd64/*.zip
    - glob: ./release/darwin-amd64/*.zip
    - glob: ./release/darwin-arm64/*.zip 
    - glob: ./release/windows-amd64/*.zip