FROM golang

WORKDIR /go/src/app
COPY . .
RUN export GO111MODULE=auto && export GOPROXY=https://goproxy.cn && go mod tidy
RUN go build -o ./bin/go_gateway

CMD ./bin/go_gateway -conf=./conf/dev/ -endpoint=dashboard