apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-gateteway-server
spec:
  replicas: 3
  selector:
    matchLabels:
      name: go-gateteway-server
  template:
    metadata:
      labels:
        name: go-gateteway-server
    spec:
      containers:
        - name: go-gateteway-server
          image: go-gateteway-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
            - containerPort: 4433
---
apiVersion: v1
kind: Service
metadata:
  name: go-gateteway-server
spec:
  ports:
    - port: 8081
      name: "http"
      targetPort: 8081
      protocol: TCP
      nodePort: 8081
    - port: 4433
      name: "https"
      targetPort: 4433
      protocol: TCP
      nodePort: 4433
  type: NodePort
  selector:
    name: go-gateteway-server