# This is base config

[base]
    debug_mode="debug"
    time_location="Asia/Chongqing"

[http]
    addr =":8880"                       # 监听地址, default ":8700"
    read_timeout = 10                   # 读取超时时长
    write_timeout = 10                  # 写入超时时长
    max_header_bytes = 20               # 最大的header大小，二进制位长度
    allow_ip = []                      # 白名单ip列表

[log]
    log_level = "trace"         #日志打印最低级别
    [log.file_writer]           #文件写入配置
        on = true
        log_path = "./logs/micro_gateway.inf.log"
        rotate_log_path = "./logs/micro_gateway.inf.log.%Y%M%D%H"
        wf_log_path = "./logs/micro_gateway.wf.log"
        rotate_wf_log_path = "./logs/micro_gateway.wf.log.%Y%M%D%H"
    [log.console_writer]        #工作台输出
        on = false
        color = false

[swagger]
    title="gin_scaffold swagger API"
    desc="This is a sample server celler server."
    host="139.9.222.12:8880"
    base_path=""
    
[cluster]
    cluster_ip="0.0.0.0"
    cluster_port="8081"
    cluster_ssl_port="4433"

[pprof]
    addr="0.0.0.0:9010"