name: Release

on:
  push:
    branches:
      - master  # 触发条件可以根据你的需求修改
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout 代码
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    # 编译 Golang 项目
    - name: Build Golang
      run: |
        make linux-amd64
        make darwin-amd64
        make darwin-arm64
        make windows-x64

    # 编译 Vue 项目
    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Build Vue
      run: |
        cd web
        npm run build:prod
        cd -

    - name: Copy dist directory
      run: |
        cp -r web/dist ./release/linux-amd64/mirco_gateway/
        cp -r web/dist ./release/darwin-amd64/mirco_gateway/
        cp -r web/dist ./release/darwin-arm64/mirco_gateway/ 
        cp -r web/dist ./release/windows-amd64/mirco_gateway/
    
    - name: Release
      run: make release

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --clean --release-notes=./Release.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}